ensure novnc chromium submodule advances

diff --git a/mw b/mw
--- a/mw
+++ b/mw
@@ -156,21 +156,19 @@ prepare_mediawiki_for_selenium() {
 DOCKER_CHROMIUM_NOVNC_PATH="$SCRIPT_PATH/docker-chromium-novnc"
 
 prepare_docker_chromium_novnc() {
-  if is_dir_empty "$DOCKER_CHROMIUM_NOVNC_PATH"; then
-    cd "$SCRIPT_PATH" || {
-      echo "Could not change directory"
-      return 1
-    }
-    if ! git submodule update --init; then
-      echo "Failed to update git submodule"
-      return 1
-    fi
-    sleep 1
+  cd "$SCRIPT_PATH" || {
+    echo "Could not change directory to $SCRIPT_PATH"
+    return 1
+  }
+  if ! git submodule update --init --recursive; then
+    echo "Failed to update git submodule"
+    return 1
   fi
+  sleep 1
   CHROMIUM_VERSION=$(docker_compose exec -u root mediawiki /usr/bin/node "./puppeteer-chromium-version-finder.js")
   echo "$CHROMIUM_VERSION"
   cd "$DOCKER_CHROMIUM_NOVNC_PATH" || {
-    echo "Could not change directory"
+    echo "Could not change directory to $DOCKER_CHROMIUM_NOVNC_PATH"
     return 1
   }
   if ! CHROMIUM_VERSION="$CHROMIUM_VERSION" ./script.sh fresh_install; then
