confirm mediawiki clone success

diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -7,7 +7,10 @@ prepare() {
   extra_compose_file_path=${1:-""}
   mkdir -p "$MEDIAWIKI_PATH"
   cd "$MEDIAWIKI_PATH" || exit
-  git clone https://gerrit.wikimedia.org/r/mediawiki/core.git . --depth=1
+  if ! git clone https://gerrit.wikimedia.org/r/mediawiki/core.git . --depth=1; then
+    echo "Failed to clone MediaWiki. Exiting."
+    exit 1
+  fi
   echo "$MW_ENV" >.env
   cp "$SCRIPT_PATH/docker-compose.override.yml" . || true
   if [ -n "$extra_compose_file_path" ] && [ -f "$extra_compose_file_path" ]; then
