update use_skin to use new method

diff --git a/use_skin b/use_skin
--- a/use_skin
+++ b/use_skin
@@ -1,13 +1,19 @@
 #!/bin/bash
 
-source "./open_special_version_page"
-source "./skins/install"
+source "./config"
+source "./make_skin_default"
 
 use_skin() {
+  cd "$SCRIPT_PATH"
   local skin_name
-  skin_name=$1
-  install "$skin_name"
-  open_special_version_page
+  skin_name="$1"
+  local skin_path
+  skin_path="skins/$1"
+  ./installer/install "$skin_path"
+  if ! make_skin_default "$skin_name"; then
+    echo "Failed to make "$skin_name" default"
+    exit 1
+  fi
 }
 
 if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
