hoist mediawiki extension/skin node dependency satisfaction to core

diff --git a/installer/install b/installer/install
--- a/installer/install
+++ b/installer/install
@@ -155,12 +155,16 @@ _install_php_and_node_dependencies() {
   if [[ ${#INSTALLED_COMPONENTS[@]} -eq 0 ]]; then
     return
   fi
-  if ! /var/local/installer/install_php_dependencies_for_components; then
-    echo "Failed to install php dependencies"
+  if ! /var/local/installer/install_php_dependencies; then
+    echo "Failed to install PHP dependencies"
     exit 1
   fi
-  if ! /var/local/installer/install_node_dependencies_for_components "${INSTALLED_COMPONENTS[@]}"; then
-    echo "Failed to install node dependencies"
+  if ! /var/local/installer/run_mediawiki_maintenance_update; then
+    echo "Mediawiki maintenance update failed. Exiting"
+    return 1
+  fi
+  if ! /var/local/installer/install_node_dependencies; then
+    echo "Failed to install Node dependencies"
     exit 1
   fi
 }
diff --git a/installer/install_node_dependencies b/installer/install_node_dependencies
--- a/installer/install_node_dependencies
+++ b/installer/install_node_dependencies
@@ -1,15 +1,25 @@
 #!/bin/bash
 
+source "/var/local/common/utility.sh"
+
+set -eu
+
 install_node_dependencies() {
-  if [ -f "package-lock.json" ]; then
-    echo "Found '$(pwd)/package-lock.json', using 'npm ci'..."
-    npm ci
-  elif [ -f "package.json" ]; then
-    echo "No package-lock.json found but found '$(pwd)/package.json', using 'npm install'..."
-    npm install
-  else
-    echo "No package-lock.json or package.json found in '$(pwd)'. Skipping npm install/ci"
+  if ! /var/local/installer/configure_npm_workspaces 2>&1 | verboseOrDotPerLine "Hoisting all skin/extension Node dependency satisfaction to MW core, if needed"; then
+    echo "Failed to configure MW core 'package.json' to use NPM workspaces wildcard paths for skins/extensions. Exiting"
+    return 1
   fi
+
+  if ! [ -f "package.json" ]; then
+    echo "Expected 'package.json' not found in '$(pwd)'"
+    return 1
+  fi
+
+  if ! npm install --legacy-peer-deps 2>&1 | verboseOrDotPerLine "NPM install"; then
+    echo "NPM install failed. Exiting"
+    return 1
+  fi
+  return 0
 }
 
 if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
