remove repo reset logic

diff --git a/installer/install b/installer/install
--- a/installer/install
+++ b/installer/install
@@ -99,9 +99,9 @@ _install_from_manifest() {
   # Generate the repository URL based on component type and name
   local repository
   repository="$GIT_CLONE_BASE_URL/$component_path"
-  
-  if ! clone_or_recursively_reset "$repository" "$component_path"; then
-    echo "Failed to clone or reset '$component_path'"
+
+  if ! git clone --recurse-submodules --progress "$repository" "$component_path" $clone_depth 2>&1 | verboseOrDotPerLine "Git clone '$repository' $clone_depth to '$component_path'" "use CLONE_DEPTH=0 for full depth"; then
+    echo "Failed to clone repository '$repository'"
     exit 1
   fi
  
diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -4,16 +4,17 @@ source "./config"
 source "./common/utility.sh"
 
 prepare() {
-  if [ -n "$MEDIAWIKI_PATH" ] && [ -d "$MEDIAWIKI_PATH" ]; then
-    docker run --rm \
-      -v "$MEDIAWIKI_PATH:/data" \
-      -u root \
-      alpine sh -c "find /data -print0 | xargs -0 -P \$(nproc) chown -h -f $(id -u):$(id -g)" \
-    2>&1 | verboseOrDotPerLine "Ensuring host user can reset/remove files"
+  mkdir -p "$MEDIAWIKI_PATH"
+  local clone_depth="--depth=${CLONE_DEPTH:-2}"
+  if [ "${CLONE_DEPTH:-1}" -eq 0 ]; then
+    local clone_depth=""
   fi
-
-  if ! clone_or_recursively_reset "$GIT_CLONE_BASE_URL/core.git" "$MEDIAWIKI_PATH"; then
-    echo "Failed to clone or reset MediaWiki. Exiting."
+  if ! (
+    cd "$MEDIAWIKI_PATH" && \
+    git clone --verbose "$GIT_CLONE_BASE_URL/core.git" . $clone_depth 2>&1 \
+    | verboseOrDotPerLine "Git clone '$GIT_CLONE_BASE_URL/core.git' $clone_depth" "use CLONE_DEPTH=0 for full depth"
+  ); then
+    echo "Failed to clone MediaWiki. Exiting."
     exit 1
   fi
   echo -e "" > "$SCRIPT_PATH/common/docker-compose.components.yml"
